name: build
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      matrix:
        java: [
          21,
        ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: crowdin action
        uses: crowdin/github-action@v2
        if: github.ref == 'refs/heads/dev'
        with:
            upload_sources: true
            download_sources: false
            push_sources: true

            upload_translations: false
            download_translations: true
            push_translations: true

            create_pull_request: true
            pull_request_base_branch_name: 'dev'
            localization_branch_name: crowdin-bot
            commit_message: 'i18n: new translations from crowdin'
            pull_request_title: 'i18n: new translations from crowdin'
            pull_request_body: 'i18n: new translations from crowdin'
            pull_request_labels: 'i18n'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
            CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }}
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
      - name: mc-publish
        uses: Kir-Antipov/mc-publish@v3.3.0
        if: github.ref == 'refs/heads/release' || contains(github.event.head_commit.message, '[publish]')
        with:
          loaders:
            fabric
            quilt

          files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar
            build/libs/*-@(dev|sources|javadocs).jar

          version-type: release
          changelog-file: CHANGELOG.md

          modrinth-id: 1TowMm2v
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"

          github-token: ${{ secrets.GITHUB_TOKEN }}

          curseforge-id: 1096649
          curseforge-token: "${{secrets.CURSEFORGE_TOKEN}}"
